name: CI

on:
  push:
    branches:
      - master

env:
  node_version: "12.x"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set NodeJS up
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - name: Cache JS dependencies
        uses: c-hive/gha-npm-cache@v1
      - name: Install JS dependencies
        run: npm install
      - name: Lint
        run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set NodeJS up
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - uses: c-hive/gha-npm-cache@v1
      - name: Install JS dependencies
        run: npm install
      - name: Build
        env:
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
        run: API_KEY="$FOOTBALL_API_KEY" npm run build
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          # https://docs.netlify.com/cli/get-started/#manual-deploys
          args: deploy --dir=dist/angular-football-web-application --prod
